name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db52fc1b9e14269159561bcc688545f5e787b367206e702028efe9df6345b885"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
