name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02d13d83234ab08bf4c553a06945012a7ade9702452daf8d53d6e0264005ca88"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
