name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ae56c7c99aaea1d5d71081a8e09fb2e555fd772c478952b2968f8940fb7c655"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
